<?php
/**
 * Implements hook_menu().
 */
function easyxdm_menu() {
  $items = array();

  $items['easyxdm-provider-script'] = array(
    'title' => 'Page reserved for firing EasyXDM provider script',
    'page callback' => 'easyxdm_render_provider_script_only',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
  );

  $items['easyxdm-test-page'] = array(
    'title' => 'EasyXDM Test Page',
    'page callback' => 'easyxdm_render_test_page',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Implements hook_library().
 */
function easyxdm_library() {
  $libraries = array();

  $libraries['easyxdm'] = array(
    'title' => 'EasyXDM',
    'website' => 'http://easyxdm.net/',
    'version' => '2.4.20.7',
    'js' => array(
      drupal_get_path('module', 'easyxdm') . '/js/easyXDM.min.js' => array(),
    ),
  );

  return $libraries;
}

/**
 * JS to initialize EasyXDM with the capacity to send and receive messages.
 *
 * Note define the JS string here, rather than a traditional JS file, so that we
 * can easily include dynamic values.
 *
 * @return string
 *   EasyXDM consumer JS, with dynamic variables.
 */
function easyxdm_script_init() {
  //////////////////////////////////////////////////////////////
  /// USE HTTPS WHEN TRANSMITTING SENSITIVE DATA!
  //////////////////////////////////////////////////////////////
  $provider_url = variable_get('easyxdm_provider_url', '');
  // $consumer_exec is stringified JavaScript to be rendered as HTML and then
  // executed when the HTML is processed by the browser. Extreme care must be
  // taken that only trusted developers submit the code which will be executed!
  $consumer_exec = variable_get('easyxdm_consumer_exec', '');

  // @todo Remove these after development.
  $provider_url = 'http://d7-provider.local/easyxdm-provider-script';
  $consumer_exec = 'console.info("EasyXDM receipt success!");';

  // Back our regularly scheduled program. @todo Remove this comment after development.
  $js = <<<EOT
    (function (Drupal) {
      'use strict';

      Drupal.easyXDM = Drupal.easyXDM || {};

      // Check whether logged in on other domain.
      if (easyXDM && easyXDM.constructor === Object) {
        var socket = new easyXDM.Socket({
          remote: '$provider_url',
          onMessage: function (message) {
            // Write the received message to the global Drupal object to be
            // accessed from JavaScripts in custom themes and modules.
            Drupal.easyXDM.inbox = message;
            $consumer_exec
          },
          onReady: function () {
            socket.postMessage('EasyXDM post success!');
          }
        });
      }
console.info('easyxdm_script_init');
console.info(Drupal.easyXDM);
    })(Drupal);
EOT;

  return $js;
}

function easyxdm_render_provider_script_only() {
  drupal_add_library('easyxdm', 'easyxdm');
  drupal_add_js(easyxdm_script_init(), array('type' => 'inline'));

  return '';
}

function easyxdm_render_test_page() {
  drupal_add_library('easyxdm', 'easyxdm');
  drupal_add_js(easyxdm_script_init(), array('type' => 'inline'));

  $output = <<<EOT
    <script>
      (function ($) {
console.info(Object.keys(Drupal));
console.info(Drupal.easyXDM);
      })(jQuery);
    </script>
EOT;

  return theme('table', array('header'=>array('$header'), 'rows'=>array(array($output))));
}
