<?php
/**
 * Implements hook_menu().
 */
function easyxdm_menu() {
  $items = array();

  $items['easyxdm-provider-script'] = array(
    'title' => 'Page reserved for firing EasyXDM provider script',
    'page callback' => 'easyxdm_render_provider_script_only',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
  );

  $items['easyxdm-provider-script-test'] = array(
    'title' => 'Fires EasyXDM provider script for EasyXDM Test Page',
    'page callback' => 'easyxdm_render_provider_script_only_test',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
  );

  $items['easyxdm-test-page'] = array(
    'title' => 'EasyXDM Test Page',
    'page callback' => 'easyxdm_render_test_page',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Implements hook_library().
 */
function easyxdm_library() {
  $libraries = array();

  $libraries['easyxdm'] = array(
    'title' => 'EasyXDM',
    'website' => 'http://easyxdm.net/',
    'version' => '2.4.20.7',
    'js' => array(
      drupal_get_path('module', 'easyxdm') . '/js/easyXDM.min.js' => array(),
    ),
  );

  return $libraries;
}

/**
 * JS to initialize EasyXDM with the capacity to send and receive messages.
 *
 * Note define the JS string here, rather than a traditional JS file, so that we
 * can easily include dynamic values.
 *
 * @return string
 *   EasyXDM consumer JS, with dynamic variables.
 */
function easyxdm_script_exec($remote_url = NULL, $init_msg = NULL, $on_msg_exec = NULL, $test = FALSE) {
  //////////////////////////////////////////////////////////////
  /// USE HTTPS WHEN TRANSMITTING SENSITIVE DATA!
  //////////////////////////////////////////////////////////////
  if (!isset($remote_url)) {
    $remote_url = variable_get('easyxdm_remote_url', '');
  }
  if (!isset($init_msg)) {
    $init_msg = variable_get('easyxdm_init_msg', '');
  }
  // $on_msg_exec is stringified JavaScript to be rendered as HTML and then
  // executed when the HTML is processed by the browser. Extreme care must be
  // taken that only trusted developers submit the code which will be executed!
  if (!isset($on_msg_exec)) {
    $on_msg_exec = variable_get('easyxdm_on_msg_exec', '');
  }

  $init_msg = addslashes($init_msg);
  $js = <<<EOT
    (function (Drupal, $) {
      'use strict';

      Drupal.easyXDM = Drupal.easyXDM || {};

      // Check whether logged in on other domain.
      if (easyXDM && easyXDM.constructor === Object) {
        var socket = new easyXDM.Socket({
          remote: '$remote_url',
          onMessage: function (message, origin) {
            // Write the received message to the global Drupal object to be
            // accessed from JavaScripts in custom themes and modules.
            Drupal.easyXDM.inbox = message;
            $on_msg_exec
          },
          onReady: function () {
            if ('$init_msg' !== '') { 
              socket.postMessage('$init_msg');
            }
          }
        });
      }
    })(Drupal, jQuery);
EOT;

  return $js;
}

function easyxdm_render_provider_script_only() {
  global $base_url;

  drupal_add_library('easyxdm', 'easyxdm');
  drupal_add_js(easyxdm_script_exec(), array('type' => 'inline'));

  return '';
}

function easyxdm_render_provider_script_only_test() {
  global $base_url;

  drupal_add_library('easyxdm', 'easyxdm');
  $on_msg_exec = <<<EOT
    if (message.indexOf("Sending consumer message from ") === 0) {
      socket.postMessage("Responding with provider message from $base_url");
    }
EOT;
  drupal_add_js(easyxdm_script_exec(NULL, NULL, $on_msg_exec), array('type' => 'inline'));

  return '';
}

function easyxdm_render_test_page() {
  global $base_url;
  global $conf;

  drupal_add_library('easyxdm', 'easyxdm');
  // @todo Make these generic after development.
  $remote_url = 'http://d7-provider.local/easyxdm-provider-script-test';
  $init_msg = 'Sending consumer message from ' . $base_url;
  $on_msg_exec = '$("#block-system-main > .content > table > tbody > tr > td:last-child").text(message);';
  drupal_add_js(easyxdm_script_exec($remote_url, $init_msg, $on_msg_exec), array('type' => 'inline'));

  $output = '<h4>X-Frame-Options must be set correctly in order for EasyXDM to communicate across domains.</h4>';
  $output .= '<h4>$conf[\'x_frame_options\']: ';
  $output .= !empty($conf['x_frame_options']) ? $conf['x_frame_options'] : '';
  $output .= '</h4>';
  $output .= theme('table', array('header'=>array('Message sent', 'Message received'), 'rows'=>array(array($init_msg, ''))));

  return $output;
}
